const data = [
  {
    product_id: 1,
    title: 'products.fjallravenFoldsack',
    price: 109.95,
    description: 'products.fjallravenDescription',
    category: 'categories.mensClothing',
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    rating: {
      rate: 3.9,
      count: 120,
    },
  },
  {
    product_id: 2,
    title: 'products.casualPremiumTShirts',
    price: 22.3,
    description: 'products.casualPremiumDescription',
    category: 'categories.mensClothing',
    image: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    rating: {
      rate: 4.1,
      count: 259,
    },
  },
  {
    product_id: 3,
    title: 'products.cottonJacket',
    price: 55.99,
    description: 'products.cottonJacketDescription',
    category: 'categories.mensClothing',
    image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    rating: {
      rate: 4.7,
      count: 500,
    },
  },
  {
    product_id: 4,
    title: 'products.casualSlimFit',
    price: 15.99,
    description: 'products.casualSlimFitDescription',
    category: 'categories.mensClothing',
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    rating: {
      rate: 2.1,
      count: 430,
    },
  },
  {
    product_id: 5,
    title: 'products.legendsNagaBracelet',
    price: 695,
    description: 'products.legendsNagaDescription',
    category: 'categories.jewelery',
    image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    rating: {
      rate: 4.6,
      count: 400,
    },
  },
  {
    product_id: 6,
    title: 'products.solidGoldPetiteMicropave',
    price: 168,
    description: 'products.solidGoldPetiteDescription',
    category: 'categories.jewelery',
    image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    rating: {
      rate: 3.9,
      count: 70,
    },
  },
  {
    product_id: 7,
    title: 'products.whiteGoldPlatedPrincess',
    price: 9.99,
    description: 'products.whiteGoldPlatedDescription',
    category: 'categories.jewelery',
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    rating: {
      rate: 3,
      count: 400,
    },
  },
  {
    product_id: 8,
    title: 'products.roseGoldPlatedDouble',
    price: 10.99,
    description: 'products.roseGoldPlatedDescription',
    category: 'categories.jewelery',
    image: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    rating: {
      rate: 1.9,
      count: 100,
    },
  },
  {
    product_id: 9,
    title: 'products.wd2TBPortableExternalHardDrive',
    price: 64,
    description: 'products.wd2TBPortableDescription',
    category: 'categories.electronics',
    image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    rating: {
      rate: 3.3,
      count: 203,
    },
  },
  {
    product_id: 10,
    title: 'products.sandiskSSDPLUS1TB',
    price: 109,
    description: 'products.sandiskSSDPLUSDescription',
    category: 'categories.electronics',
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    rating: {
      rate: 2.9,
      count: 470,
    },
  },
  {
    product_id: 11,
    title: 'products.siliconPower256GBSSD',
    price: 109,
    description: 'products.siliconPowerDescription',
    category: 'categories.electronics',
    image: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
    rating: {
      rate: 4.8,
      count: 319,
    },
  },
  {
    product_id: 12,
    title: 'products.wd4TBGamingDrive',
    price: 114,
    description: 'products.wd4TBGamingDriveDescription',
    category: 'categories.electronics',
    image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    rating: {
      rate: 4.8,
      count: 400,
    },
  },
  {
    product_id: 13,
    title: 'products.acerSB220Qbi21.5inchesFullHD',
    price: 599,
    description: 'products.acerSB220QbiDescription',
    category: 'categories.electronics',
    image: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
    rating: {
      rate: 2.9,
      count: 250,
    },
  },
  {
    product_id: 14,
    title: 'products.samsung49InchCurvedGamingMonitor',
    price: 999.99,
    description: 'products.samsung49InchCurvedDescription',
    category: 'categories.electronics',
    image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    rating: {
      rate: 2.2,
      count: 140,
    },
  },
  {
    product_id: 15,
    title: 'products.biylaclesenWomens3in1SnowboardJacket',
    price: 56.99,
    description: 'products.biylaclesenWomens3in1Description',
    category: 'categories.womensClothing',
    image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    rating: {
      rate: 2.6,
      count: 235,
    },
  },
  {
    product_id: 16,
    title: 'products.lockAndLoveWomensRemovableJacket',
    price: 29.95,
    description: 'products.lockAndLoveWomensDescription',
    category: 'categories.womensClothing',
    image: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
    rating: {
      rate: 2.9,
      count: 340,
    },
  },
  {
    product_id: 17,
    title: 'products.rainJacketWomenWindbreaker',
    price: 39.99,
    description: 'products.rainJacketWomenDescription',
    category: 'categories.womensClothing',
    image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    rating: {
      rate: 3.8,
      count: 679,
    },
  },
  {
    product_id: 18,
    title: 'products.mbjWomensSolidShortSleeveBoatNeck',
    price: 9.85,
    description: 'products.mbjWomensSolidShortDescription',
    category: 'categories.womensClothing',
    image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    rating: {
      rate: 4.7,
      count: 130,
    },
  },
  {
    product_id: 19,
    title: 'products.opnaWomensShortSleeveMoisture',
    price: 7.95,
    description: 'products.opnaWomensShortDescription',
    category: 'categories.womensClothing',
    image: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
    rating: {
      rate: 4.5,
      count: 146,
    },
  },
  {
    product_id: 20,
    title: 'products.danvouyWomensTShirtCasualCottonShort',
    price: 12.99,
    description: 'products.danvouyWomensTShirtDescription',
    category: 'categories.womensClothing',
    image: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    rating: {
      rate: 3.6,
      count: 145,
    },
  },
];

export default data;
